export const MUSIC_GENRES = [
  "dance pop",
  "post-teen pop",
  "electropop",
  "indie poptimism",
  "hip hop",
  "southern hip hop",
  "gangster rap",
  "trap",
  "album rock",
  "classic rock",
  "permanent wave",
  "hard rock",
  "tropical",
  "latin pop",
  "reggaeton",
  "latin hip hop",
  "urban contemporary",
  "hip pop",
  "neo soul",
  "electro house",
  "big room",
  "pop edm",
  "progressive electro house",
];

export const ARTISTS = [
  "The Black Eyed Peas",
  "MEDUZA",
  "Billie Eilish",
  "Regard",
  "KAROL G",
  "Shawn Mendes",
  "Maroon 5",
  "The Weeknd",
  "Juice WRLD",
  "Justin Bieber",
  "Tones and I",
  "Lewis Capaldi",
  "J Balvin",
  "Selena Gomez",
  "Anuel AA",
  "Sam Smith",
  "Ed Sheeran",
  "Harry Styles",
  "Travis Scott",
  "Rauw Alejandro",
  "Post Malone",
  "Dua Lipa",
  "blackbear",
  "Dan + Shay",
  "Y2K",
  "Camila Cabello",
  "Trevor Daniel",
  "Tyga",
  "Don Toliver",
  "DaBaby",
  "Future",
  "Roddy Ricch",
  "Lil Uzi Vert",
  "Bad Bunny",
  "Dalex",
  "Arizona Zervas",
];
